--- #YAML:1.0
name:                Text-Netstring
version:             0.07
abstract:            Perl module for manipulation of netstrings
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
